### ISSUE TITLE
bootstrap: bootstrap.css.map missing

### ISSUE THREAD

**Issue by Signum** [padrino/padrino-recipes#64]
I just used "padrino gen plugin bootstrap" but apparently I get a 404 on the bootstrap.css.map file. I'm no Bootstrap expert but perhaps the https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap-theme.css.map file needs to be fetched, too.

**Comment by RohanDas28** [comment]
> 
> 
> from `bootstrap-theme.css` remove last line `/*# sourceMappingURL=bootstrap-theme.css.map */`

It Worked! Thanks dude
