### ISSUE TITLE
Unable to install bootsrap gem

### ISSUE THREAD

**Issue by collegeimprovements** [padrino/padrino-recipes#84]
I'm getting the following error while trying to install the bootstrap gem with `padrino-gen plugin bootstrap` command.
```
 apply  https://raw.github.com/padrino/padrino-recipes/master/plugins/bootstrap_plugin.rb
  The template at https://raw.github.com/padrino/padrino-recipes/master/plugins/bootstrap_plugin.rb could not be found!
```
Please help.

**Comment by wikimatze** [comment]
It's fixed by now (maybe it was a temporary failure for bootstrap because we're grabbing the sources from `https://raw.github.com/twbs/bootstrap/master/dist/*`).
